exclude: '.git|.tox|.trash|lammps_wrapper'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
